[workspace]
members = [
    "drillhash",
    "examples",
    "program"
]

[workspace.dependencies]
blake3 = "1.5"
bytemuck = "1.15.0"
drillhash = { path = "drillhash" }
enum_dispatch = "0.3.13"
num_enum = "0.5"
num-traits = "0.2.18"
primes = "0.3.0"
sha3 = "0.10.8"
solana-program = "1.18.11"
solana-program-test = "1.18.11"
solana-sdk = "1.18.11"
strum = { version = "0.26.2", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
