[package]
name = "drillhash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.4"
num-traits = "0.2.18"
sha3 = "0.10.8"
tokio = { version = "1.37.0", features = ["full"] }
