[package]
name = "drillx"
version = "0.1.0"
description = "Drillx is an asic-resistant hashing algorithm for Ore cryptocurrency mining."
edition = "2021"
license = "Apache-2.0"
homepage = "https://ore.supply"
documentation = "https://ore.supply"
repository = "https://github.com/hardhatchad/drillx"
readme = "../README.md"
keywords = ["solana", "crypto", "mining"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "drillx"

[features]
default = ["blake3", "sha3"]
benchmark = []
solana = ["solana-program"]

[dependencies]
blake3 = { workspace = true, optional = true }
enum_dispatch = { workspace = true }
fixed = { workspace = true }
num_enum = { workspace = true }
num-traits = { workspace = true }
periodic-array = { workspace = true }
primes = { workspace = true }
rand = { workspace = true }
sha3 = { workspace = true, optional = true }
solana-program = { workspace = true, optional = true }
strum = { workspace = true }
