[package]
name = "drillhash-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "drillhash"

[features]
no-entrypoint = []
default = []

[dependencies]
bytemuck = "1.15.0"
num-bigint = "0.4.4"
num-traits = "0.2.18"
sha3 = "0.10.8"
solana-program = "1.18.11"

[dev-dependencies]
solana-program-test = "1.18.11"
solana-sdk = "1.18.11"
tokio = { version = "1.35", features = ["full"] }
